// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flash_job/feature/data/models/user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CountryModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
